load_module /usr/lib/nginx/modules/ndk_http_module.so;
load_module /usr/lib/nginx/modules/ngx_http_lua_module.so;

worker_processes  1;
user root;

events {
    worker_connections  1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        access_log /root/waf-demo/logs/access.log;
        error_log  /root/waf-demo/logs/error.log;

        location / {
            access_by_lua_file /root/waf-demo/waf/waf.lua;

            root /root/waf-demo/html;
            index index.html;
        }
    }
}